language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.1
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225"
  - "find . -name '*.py' | xargs pyflakes" 
  - mysql -e 'create database thegreco;'
  - python manage.py syncdb --noinput
script:
  - python manage.py test common rating
notifications:
  email:
    recipients:
      - jobelenus@gmail.com
    on_success: [never]
    on_failure: [always]
